workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        APP_NAME: myAudioApp
      xcode: 15.2
    scripts:
      - name: Instalar dependências
        script: |
          npm install

      - name: Verificar esquema compartilhado
        script: |
          xcodebuild -project ios/$APP_NAME.xcodeproj -list

      - name: Compilar e arquivar o app
        script: |
          xcodebuild -project ios/$APP_NAME.xcodeproj \
            -scheme $APP_NAME \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/$APP_NAME.xcarchive \
            clean archive

      - name: Exportar IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/$APP_NAME.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported

    artifacts:
      - build/**/exported/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
