workflows:
  ios-build:
    name: Build iOS for MyAudioApp
    environment:
      vars:
        XCODE_WORKSPACE: "myAudioApp.xcworkspace"
        XCODE_SCHEME: "myAudioApp"
      xcode: latest
      cocoapods: default
      node: 18.16.0
    scripts:
      - name: Instalar dependências Node
        script: |
          npm install
      - name: Instalar Pods iOS
        script: |
          cd ios
          pod install
      - name: Criar Scheme se não existir
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" || {
            echo "Criando scheme compartilhado..."
            xcodebuild -project myAudioApp.xcodeproj -scheme myAudioApp -showBuildSettings
          }
      - name: Verificar schemes após adicionar .xcscheme
        script: |
          cd ios
          xcodebuild -list -project myAudioApp.xcodeproj
      - name: Build iOS
        script: |
          cd ios
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/myAudioApp.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            CODE_SIGN_STYLE=Automatic \
            clean archive
    artifacts:
      - build/**/myAudioApp.xcarchive
