workflows:
  ios-build:
    name: iOS Build (React Native)
    environment:
      xcode: latest
      node: 18.18.2
      cocoapods: default
      vars:
        APP_NAME: "myAudioApp"
    scripts:
      - name: Instalar dependências
        script: |
          npm install
      - name: Verificar esquema compartilhado
        script: |
          xcodebuild -project $APP_NAME.xcodeproj -list
      - name: Compilar e arquivar o app
        script: |
          xcodebuild -project $APP_NAME.xcodeproj \
            -scheme $APP_NAME \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/$APP_NAME.xcarchive \
            clean archive
      - name: Exportar IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/$APP_NAME.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported
    artifacts:
      - build/**/exported/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
    publishing:
      email:
        recipients:
          - igor.arena35@gmail.com
